package com.github.sasd97.upitter.constants;

/**
 * Created by Alexadner Dadukin on 23.06.2016.
 */
public interface IntentKeysConstants {

    String RECEIVED_SMS_CODE = "RECEIVED_SMS_CODE";
    String RECEIVED_SMS_CODES = "RECEIVED_SMS_CODES";
    String RECEIVED_PHONE = "RECEIVED_PHONE";

    String RECEIVED_TEMPORARY_TOKEN = "RECEIVED_TEMPORARY_TOKEN";

    String CATEGORIES_ATTACH = "CATEGORIES_ATTACH";

    //Gallery constants region
    String GALLERY_MULTI_SELECTION_MODE = "GALLERY_MULTI_SELECTION_MODE";
    String GALLERY_MULTI_SELECT_ITEMS_AMOUNT = "GALLERY_MULTI_SELECT_ITEMS_AMOUNT";

    String GALLERY_ALBUM_ATTACH = "GALLERY_ALBUM_ATTACH";

    String MULTI_SELECT_ATTACH ="MULTI_SELECT";
    String PATH_ATTACH = "PATH_ATTACH";
    String POSITION_ATTACH = "POSITION_ATTACH";
    String LIST_ATTACH = "LIST_ATTACH";

    int FIRST_POSITION = 0;
    String PUT_IMAGE_PATH = "IMAGE_PATH";
    String PUT_CROPPED_IMAGE = "IMAGE_CROPPED";
    //Endregion
}
